version: 2.1
workflows:
  test:
    jobs:
      - deploy:
          context: cloudflare
          filters:
            branches:
              only:
                - main

# Just for reusing below
step_defs:
  - run: &node_version
      name: Set Node version
      command: |
        nvm install v16
        nvm alias default v16
        echo "nvm use default" >> $BASH_ENV
  - run: &check_version
      name: Check Node version
      command: node -v | grep v16

jobs:
  deploy:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: yarn
      - run:
          name: Build relay image
          command: docker build . -t jchancehud/zketh:latest
      - run:
          name: Push relay image
          command: |
            echo $DOCKER_TOKEN | docker login -u jchancehud --password-stdin
            docker push jchancehud/zketh:latest
            rm /home/circleci/.docker/config.json
      - run:
          name: Trigger service update
          command: curl -X POST https://devops.unirep.io/api/webhooks/b3a07d46-3808-40cc-9d8b-926fdf7ea71b
      - run:
          name: Set frontend config
          command: echo 'export const KEY_SERVER = "https://relay.zketh.io/build/";export const WS_SERVER="https://relay.zketh.io/ws"' > packages/frontend/src/config.js
      - run:
          name: Build frontend
          command: yarn frontend build --mode production
      - run:
          name: Publish frontend
          command: |
            cd packages/frontend
            npx wrangler@2.1 publish
  lint:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install Packages
          command: yarn
      - run:
          name: Test
          command: yarn lint --check
